%Example template for creating an RNA tapestry
%refer to 

construct_name='Your library name'; %Choose a name
offset = 40; %Declare where you want to begin your mutations to avoid the T7 promoter and 5' flanking region
which_muts = [1:226]; %Declare span of mutations
which_libraries = [1]; %Declare the class of mutations you would like to make.
%Insert your sequence here
sequence='TTCTAATACGACTCACTATAGGAAAGGAAAGGGAAAGAAAGTTGAAGACTGCAGGAGAGTGGTTGTTAACCAGATTTTAACATCTGAGCCAAATAACCCGCCGAAGAAGTAAATCTTTCAGGTGCATTATTCTTAGCCATATATTGGCAACGAATAAGCGAGGACTGTAGTTGGAGGAACCTCTGGAGAGAACCGTTTAATCGGTCGCCGAAGGAGCAAGCTCTGCGCATATGCAGAGTGAAACTCTCAGGCAAAAGGACAGAGGAAAAACAAACCAAACCAAAGAAACAACAACAACAAC'; 
%Insert all of your primers
primers={'TTCTAATACGACTCACTATAGGAAAGGAAAGGGAAAGAAAGTTGA','ACTCTCCTGCAGTCTTCAACTTTCTTTCCCTTTCCTTTCCTA','AAGACTGCAGGAGAGTGGTTGTTAACCAGATTTTAACATCTGAGCCAAATAACCCG',...
    'GCTAAGAATAATGCACCTGAAAGATTTACTTCTTCGGCGGGTTATTTGGCTCA','CAGGTGCATTATTCTTAGCCATATATTGGCAACGAATAAGCGAGGACTGTAGT','TCCTTCGGCGACCGATTAAACGGTTCTCTCCAGAGGTTCCTCCAACTACAGTCCTCGCT','GGTCGCCGAAGGAGCAAGCTCTGCGCATATGCAGAGTGAAACTCTCAGGCAAAAGGACA','GTTGTTGTTGTTGTTTCTTTGGTTTGGTTTGTTTTTCCTCTGTCCTTTTGCCTGAGA'};

% Lets make them
sequences_to_order = single_mutant_library( primers, sequence, offset, which_muts, which_libraries,construct_name );
% This creates *.eps files for you
output_sequences_to_order_96well_diagram( sequences_to_order, primers, construct_name );