primers = { 'TTCTAATACGACTCACTATAGGTCATAAATAACGAAAGTTGAAGACTGCAGG',
	    'AAAATCTGGTTAACAACCAGTCTCCTGCAGTCTTCAACTTTCGTTATT',
	    'TTAACCAGATTTTAACATCTGAGCCAAATAACCCGCCGAAGAAGTAAA',
	    'TAAGAATAATGCACCTGAAAGATTTACTTCTTCGGCGGGTTATTTGGC',
	    'GGTGCATTATTCTTAGCCATATATTGGCAACGAATAAGCGAGGACTGTAGTTGGAGGA',
	    'GACCGATTAAACGGTTCTCTCCAGAGGTTCCTCCAACTACAGTCCT',
	    'AACCGTTTAATCGGTCGCCGAAGGAGCAAGCTCTGCGCATATGCAGAGTG',
	    'GTCCTTTTGCCTGAGAGTTTCACTCTGCATATGCGCAGAGCT',
	    'AAACTCTCAGGCAAAAGGACAGAGGAAAACCAAACCAAAGAAAC',
	    'GTTGTTGTTGTTGTTTCTTTGGTTTGGTTTTCCTCTGTCCTTTTGC' };

template = 'TTCTAATACGACTCACTATAGGTCATAAATAACGAAAGTTGAAGACTGCAGGAGACTGGTTGTTAACCAGATTTTAACATCTGAGCCAAATAACCCGCCGAAGAAGTAAATCTTTCAGGTGCATTATTCTTAGCCATATATTGGCAACGAATAAGCGAGGACTGTAGTTGGAGGAACCTCTGGAGAGAACCGTTTAATCGGTCGCCGAAGGAGCAAGCTCTGCGCATATGCAGAGTGAAACTCTCAGGCAAAAGGACAGAGGAAAACCAAACCAAAGAAACAACAACAACAAC';

order_primers_along_template( primers, template );

template_new = ...
    'TTCTAATACGACTCACTATAGGTCATAAATAACCAAAGTTGAAGACTGCAGGAGACTGGTTGTTAACCAGATTTTAACATCTGAGCCAAATAACCCGCCGAAGAAGTAAATCTTTCAGGTGCATTATTCTTAGCCATATATTGGCAACGAATAAGCGAGGACTGTAGTTGGAGGAACCTCTGGAGAGAACCGTTTAATCGGTCGCCGAAGGAGCAAGCTCTGCGCATATGCAGAGTGAAACTCTCAGGCAAAAGGACAGAGGAAAACCAAACCAAAGAAACAACAACAACAAC'
design_primers( template_new );

