primers= ...
    {'TTCTAATACGACTCACTATAGGCCAAAACAACGGAATTGCGGGAAAGGGGTCAACAGCCG','GGCCATCTCAAAGTTTCCCCTGAGACTTGGTACTGAACGGCTGTTGACCCCTTTCCCG','GGGAAACTTTGAGATGGCCTTGCAAAGGGTATGGTAATAAGCTGACGGAC','GTTGACTTAGGACTTGGCTGCGTGTTAGGACCATGTCCGTCAGCTTATTACCATAC','CAGCCAAGTCCTAAGTCAACAGATCTTCTGTTGATATGGATGCAGTT','GTTGTTGTTGTTGTTTCTTTGGTTTGGTTTTGAACTGCATCCATATCAACAGAAG'};

mutate_primers( primers, 'R1align.txt' )
